blogTitle = "My Useless Blog"
blogUrl = "https://www.kapadiya.net"
authorName = "Vikas Kapadiya"
authorBio = "Hi, I’m Vikas. I’ve been writing code for over a decade (yikes). When I’m not programming, you’ll find me spending time with my friends, playing FPS Games or eating pizza. You'll never find me at gym."
authorPic = "avatar.jpg"
linkPrefix = ""
github_url = "https://github.com/vikas5914"
twitter_url = "https://twitter.com/kapadiyavikas"
instagram_url = "https://www.instagram.com/kapadiyavikas/"
gaCode = "UA-47470775-1"
disqusShortname = "kapadiya"
